# -*- coding: utf-8 -*-
"""Send email using Mailgun - teacher version

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dP2RcsnN2teu1DIuePGM2NDjwRw5TgRb

# **Sending emails using Mailgun**

## Create account

*   Go to https://signup.mailgun.com/new/signup
*   Sign up using your personal email - the college one will not work
*   Don't bother with a credit card - this still gives you a basic account
*   Once logged in to the Mailgun dashboard, select *Sending* from the left side
*   You should have a domain - click on it
*   Select the API option then Python
*   Copy the Python code
*   You will need to edit the following 4 things
    1. Copy the API base url into your code - it will be something like this (**yours will be different**)
        > https://api.mailgun.net/v3/sandbox6e61a3bda725466f9bd28a192719f652.mailgun.org/messages
    1. Copy the API key into your code - it will be something like this (**yours will be different**)
        > fb6f5a96c1a0ef1fe684c4de90db5fb8-2ac825a1-c721429e
    1. Change the *from* part to be something like this
        > "from": "andrew.chisholm@hsdc.ac.uk"
    1. Change the *to* part to something like this
        > "to": "awchisholm@gmail.com"
* You have to add the email addresses that you can send to. Do this by going to *Authorized Recipients* and add the email address you want to send to. You will need to accept the message the first time at the recipient.

## Run the code

Once all is set up, run the code to call the function. If you get 

> <Response [200]>




it worked!

## Sending emails as part of a booking system

To use this in a booking system, you would need to modify the function to take parameters so that it is more flexible. You would probably pass the data as a parameter and use this in the function.

## More complicated examples

You can send attachments or inline images or both. Go here to read all about it.

https://documentation.mailgun.com/en/latest/ 

This link gives specific details for sending.

https://documentation.mailgun.com/en/latest/api-sending.html#sending
"""

import requests
def send_simple_message():
    return requests.post(
        "https://api.mailgun.net/v3/sandbox67aabdf82dd44215aea745bebec5ce9c.mailgun.org/messages",
        auth=("api", "334d0e4bdf2b04a647419df29c81413c-2ac825a1-7d8ce384"),
    data={"from": "andrew.chisholm@hsdc.ac.uk",
            "to": "awchisholm@gmail.com",
            "subject": "Hello",
            "text": "Sending an email"})

send_simple_message()

def send_complex_message():
    return requests.post(
        "https://api.mailgun.net/v3/sandbox67aabdf82dd44215aea745bebec5ce9c.mailgun.org/messages",
        auth=("api", "334d0e4bdf2b04a647419df29c81413c-2ac825a1-7d8ce384"),
        files=[("attachment", ("Send email using Mailgun - teacher version.ipynb", open("Send email using Mailgun - teacher version.ipynb","rb").read())),
               ("attachment", ("Send email using Mailgun - teacher version.py", open("Send email using Mailgun - teacher version.py","rb").read()))],
        data={"from": "andrew.chisholm@hsdc.ac.uk",
              "to": ["awchisholm@gmail.com", "andrew.chisholm@hsdc.ac.uk"],
              #"cc": "baz@example.com",
              #"bcc": "bar@example.com",
              "subject": "Hello",
              "text": "Testing some Mailgun awesomness!",
              "html": "<html>HTML version of the body</html>"})
    
send_complex_message()

def send_inline_message():
    return requests.post(
        "https://api.mailgun.net/v3/sandbox67aabdf82dd44215aea745bebec5ce9c.mailgun.org/messages",
        auth=("api", "334d0e4bdf2b04a647419df29c81413c-2ac825a1-7d8ce384"),
        files=[("inline", open("/content/intoxicate.jpg", mode='rb'))],
        data={"from": "andrew.chisholm@hsdc.ac.uk",
              "to": ["awchisholm@gmail.com"],
              "subject": "Hello",
              "text": "Testing some Mailgun awesomness!",
              "html": "<html>HTML version of the body</html>"})

send_inline_message()



send_complex_message()

data={
    "from": "andrew.chisholm@hsdc.ac.uk",
    "to": "awchisholm@gmail.com",
    "subject": "Hello",
    "text": "Parameter passing"
}
def send_message(data):
    return requests.post(
        "https://api.mailgun.net/v3/sandbox67aabdf82dd44215aea745bebec5ce9c.mailgun.org/messages",
        auth=("api", "334d0e4bdf2b04a647419df29c81413c-2ac825a1-7d8ce384"),
        data=data)

send_message(data)

open("000023.png", mode='rb')
