CREATE TABLE "customer" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT,
	"Height"	REAL
);
CREATE TABLE "booking" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Details"	TEXT,
	"CustomerId"	INTEGER,
	CONSTRAINT "customerid_fk" FOREIGN KEY("CustomerId") REFERENCES "customer"("Id")
);
